# Generated by Django 3.2.13 on 2022-05-14 08:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
